steps:
  # Step 1: Create a temporary file with variables that will be copied into the Docker build
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create .env file with actual values from substitutions
        echo "RESEND_API_KEY=${_RESEND_API_KEY}" >> build.env
        echo "NEXT_PUBLIC_PASSKEY_ENC_SALT=${_NEXT_PUBLIC_PASSKEY_ENC_SALT}" >> build.env
        echo "NEXT_PUBLIC_VERIFIER_SECRET=${_NEXT_PUBLIC_VERIFIER_SECRET}" >> build.env
        cat build.env

  # Build the container image - using --env-file instead of build-args
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'ENV_FILE=build.env',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}',
      '-f', 'Dockerfile.dev',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']

substitutions:
  _SERVICE_NAME: referral-dashboard
  _RESEND_API_KEY: ''
  _NEXT_PUBLIC_PASSKEY_ENC_SALT: ''
  _NEXT_PUBLIC_VERIFIER_SECRET: ''

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
